// Live specimens for the Graph Paradigm docs (ARC-167): every paradigm × every lens rendered by the
// REAL renderer through the chrome-less harness, then frozen as static HTML that loads ONLY the
// package CSS — proof that @typegram/graph alone draws what Workbench draws.
//   pnpm build && pnpm preview   (or any server on BASE)   then: pnpm specimens
import { mkdirSync, writeFileSync } from 'node:fs';
import { chromium } from '@playwright/test';
const BASE = process.env['BASE'] ?? 'http://localhost:4173';
const OUT = 'packages/typegram/docs/specimens';
const PARADIGMS = ['architecture', 'workflow', 'sequence', 'dataflow', 'state'];
const LENSES = ['design', 'simulate', 'analyze'];
const CSS = ['tokens/fonts.css', 'tokens/colors.css', 'tokens/typography.css', 'tokens/spacing.css', 'tokens/base.css', 'tokens/graph.css', 'tokens/motion.css', 'components/components.css', 'components/graph/graph.css', 'tokens/themes.css', 'tokens/paradigms.css', 'components/graph/paradigms/paradigms.css', 'components/graph/telemetry.css'];
mkdirSync(OUT, { recursive: true });
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: 1400, height: 820 } });
const index = [];
for (const pid of PARADIGMS) for (const lens of LENSES) {
  const url = `${BASE}/?static=1&p=${pid}&z=working&mode=${lens}`;
  await p.goto(url); await p.waitForSelector('.tg-gnode'); await p.waitForTimeout(500);
  const html = await p.evaluate(() => document.querySelector('.tg-gcanvas').outerHTML);
  const name = `${pid}-${lens}`;
  await p.screenshot({ path: `${OUT}/${name}.png` });
  const links = CSS.map(f => `<link rel="stylesheet" href="../../${f}">`).join('\n');
  writeFileSync(`${OUT}/${name}.html`, `<!doctype html>\n<html lang="en" data-theme="dark"><head><meta charset="utf-8"><title>${pid} · ${lens} · Typegram Graph Paradigm specimen</title>\n${links}\n<style>html,body{margin:0;height:100%;background:var(--surface-page)}.tg-gcanvas{height:100vh}</style></head>\n<body>\n<!-- generated by scripts/specimens.mjs from ${url} · package CSS only, no application code -->\n${html}\n</body></html>\n`);
  index.push({ name, pid, lens });
}
writeFileSync(`${OUT}/index.html`, `<!doctype html>\n<html lang="en" data-theme="dark"><head><meta charset="utf-8"><title>Typegram Graph Paradigm · specimens</title>${CSS.map(f => `<link rel="stylesheet" href="../../${f}">`).join('')}<style>body{margin:0;padding:24px;background:var(--surface-page);color:var(--text-body);font-family:var(--font-mono);font-size:12px}h1{font-family:var(--font-sans);font-size:18px}table{border-collapse:collapse}td,th{padding:6px 10px;border-bottom:1px solid var(--border-subtle);text-align:left}a{color:var(--link)}img{width:280px;display:block;border:1px solid var(--border-subtle)}</style></head><body><h1>Graph Paradigm · live specimens</h1><p>five paradigms × three lenses, rendered by Workbench's renderer and frozen with the package CSS only · regenerate with <code>pnpm specimens</code></p><table><tr><th>paradigm</th>${LENSES.map(l => `<th>${l}</th>`).join('')}</tr>${PARADIGMS.map(pid => `<tr><td>${pid}</td>${LENSES.map(l => `<td><a href="${pid}-${l}.html"><img src="${pid}-${l}.png" alt="${pid} · ${l}"></a></td>`).join('')}</tr>`).join('')}</table></body></html>\n`);
await b.close();
console.log('specimens:', index.length, '→', OUT);
